### ISSUE TITLE
run_test.sh fails on Mac (Darwin)

### ISSUE THREAD

**Issue by golharam** [common-workflow-language/cwl-v1.2#104]
When following directions here, https://www.commonwl.org/v1.2/, to execute the test script, run_test.sh fails on Mac (Darwin):
```
$ ./run_test.sh 
./run_test.sh: line 160: greadlink: command not found
--- Running CWL Conformance Tests v1.2 on  ---
./run_test.sh: line 144: : command not found
usage: cwltest [-h] --test TEST [--basedir BASEDIR] [-l] [-n N] [-s S] [-N N]
               [-S S] [--tool TOOL] [--only-tools] [--tags TAGS] [--show-tags]
               [--junit-xml JUNIT_XML] [--junit-verbose]
               [--test-arg cache==--cache-dir] [-j J] [--verbose]
               [--classname CLASSNAME] [--timeout TIMEOUT]
               [--badgedir BADGEDIR] [--version]
               ...
cwltest: error: argument --tool: expected one argument

1 tool tests failed
```

When I run the script with 'bash -ex', the if statement resolves to '[' Darwin = Linux ']':
```
+ '[' Darwin = Linux ']'
++ greadlink -f /Users/golharr/workspace/CWL/env/bin/cwl-runner
./run_test.sh: line 160: greadlink: command not found
```

Mac has readlink, not greadlink, so a check for Darwin is necessary, in addition to Linux.  In fixing this, the parameter '-f' to readlink does not exist on Mac/Darwin.

**Comment by golharam** [comment]
Pull Request https://github.com/common-workflow-language/cwl-v1.2/pull/105 enabled run_test.sh to run on Mac/Darwin

**Comment by tom-tan** [comment]
run_test.sh implicitly requires coreutils on macOS and it seems to be intended.
See: common-workflow-language/common-workflow-language#152 and common-workflow-language/common-workflow-language#316
