### ISSUE TITLE
fix cwloutput-nolimit test's outputs to match the cwl.output.json results

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-v1.2#120]
https://github.com/common-workflow-language/cwl-v1.2/blob/5f27e234b4ca88ed1280dedf9e3391a01de12912/tests/loadContents/test-index.yaml#L2 → https://github.com/common-workflow-language/cwl-v1.2/blob/5f27e234b4ca88ed1280dedf9e3391a01de12912/tests/loadContents/cwloutput-nolimit.cwl#L11

missing an output named `bigstring` of type `string`

**Comment by GlassOfWhiskey** [comment]
@mr-c this seems solved by [121](https://github.com/common-workflow-language/cwl-v1.2/pull/121). Can we close it?
