### ISSUE TITLE
Wrong assumption on conformance test 309 (secontaryfiles/rename-inputs.cwl)

### ISSUE THREAD

**Issue by GlassOfWhiskey** [common-workflow-language/cwl-v1.2#127]
This is a portion of the content of the `rename-inputs.cwl` file for conformance test 309:

```
inputs:
- id: inputWithSecondary
  type: File
  doc: |
    This input will with a secondary file `.accessory`. You could create these files (and its accessory) with:
    ```bash
    touch secondary_file_test.txt
    touch secondary_file_test.txt.accessory
    ```
  secondaryFiles:
    - .accessory
    - |
      ${
        function resolveSecondary(base, secPattern) {
          if (secPattern[0] == '^') {
            var spl = base.split('.');
            var endIndex = spl.length > 1 ? spl.length - 1 : 1;
            return resolveSecondary(spl.slice(undefined, endIndex).join("."), secPattern.slice(1));
          }
          return base + secPattern;
        }
        return [{
            "class": "File",
            "location": self.secondaryFiles[0].location,
            "basename": resolveSecondary(self.basename, '^.accessory')
        }];
      }
```

The JavaScript expression of the second entry in the `secondaryFiles` list explicitly refers to `self.secondaryFiles[0]`, which must have been evaluated BEFORE starting to evaluate the expression.

In cwltool (and I assume also in other CWL-compliant tools) this works correctly because the `secondaryFiles` list is evaluated sequentially and in order. This is not a requirement for the CWL standard, but an out-of-order evaluation makes the test fail.

However, relying on a particular evaluation order can lead to an undesired behaviour also in sequential evaluations. For example, the following expression, which should apparently be as fine as the previous one. fails also within cwltool:

```
inputs:
- id: inputWithSecondary
  type: File
  doc: |
    This input will with a secondary file `.accessory`. You could create these files (and its accessory) with:
    ```bash
    touch secondary_file_test.txt
    touch secondary_file_test.txt.accessory
    ```
  secondaryFiles:
    - |
      ${
        function resolveSecondary(base, secPattern) {
          if (secPattern[0] == '^') {
            var spl = base.split('.');
            var endIndex = spl.length > 1 ? spl.length - 1 : 1;
            return resolveSecondary(spl.slice(undefined, endIndex).join("."), secPattern.slice(1));
          }
          return base + secPattern;
        }
        return [{
            "class": "File",
            "location": self.secondaryFiles[1].location,
            "basename": resolveSecondary(self.basename, '^.accessory')
        }];
      }
    - .accessory
```

**Comment by tetron** [comment]
I am running into trouble with this test as well, I need to investigate.

**Comment by tetron** [comment]
Yea, this is actually testing spec-conforming behavior.  I have a PR where I propose changing it so that references a separate input parameter, while still tests the ability to use a script to return a File object with an alternate basename:

```
inputs:
- id: inputWithSecondary
  type: File
  doc: |
    This input will with a secondary file `.accessory`. You could create these files (and its accessory) with:
    ```bash
    touch secondary_file_test.txt
    touch secondary_file_test.txt.accessory
    ```
  secondaryFiles:
    - |
      ${
        function resolveSecondary(base, secPattern) {
          if (secPattern[0] == '^') {
            var spl = base.split('.');
            var endIndex = spl.length > 1 ? spl.length - 1 : 1;
            return resolveSecondary(spl.slice(undefined, endIndex).join("."), secPattern.slice(1));
          }
          return base + secPattern;
        }
        return [{
            "class": "File",
            "location": inputs.accessory.location,
            "basename": resolveSecondary(self.basename, '^.accessory')
        }];
      }
- id: accessory
  type: File
```

**Comment by GlassOfWhiskey** [comment]
Fixed by [128](https://github.com/common-workflow-language/cwl-v1.2/pull/128).
