### ISSUE TITLE
Tighten up wording around inheritance of requirements/hints from workflow to step

### ISSUE THREAD

**Issue by rupertnash** [common-workflow-language/cwl-v1.2#131]
In the concepts doc section "Requirements and hints"
https://github.com/common-workflow-language/cwl-v1.2/blob/ed32d52db36fd731a99ea8bf8d2a9a3d338f0f19/concepts.md#L471

> If the same process requirement appears at different levels of the
> workflow, the most specific instance of the requirement is used, that is,
> an entry in `requirements` on a process implementation such as
> CommandLineTool will take precedence over an entry in `requirements`
> specified in a workflow step, and an entry in `requirements` on a workflow
> step takes precedence over the workflow.  Entries in `hints` are resolved
> the same way.

This could do with tightening up.

First the use of "the same": the text clearly means "same-named" (rather than a requirement that requires equal requirements e.g. exactly the same environment variable key/value pairs).

Second it could do with clarifying this is wholesale replacement of the requirement, not doing key-wise updates (as might be expected in the case of `EnvVarRequirement`)

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-v1.2/pull/132
