### ISSUE TITLE
Workflow output type appears to be incorrect in tests cond-wf-011, cond-wf-011_nojs

### ISSUE THREAD

**Issue by jdidion** [common-workflow-language/cwl-v1.2#147]
In these two tests, the expected output type is `array[array[array[string]]]`, however the expected output value has nulls in the inner array. Therefore, it seems that the expected output type should be `array[array[array[string?]]]`.

```
out1:
      [
        [
          [ null, "112", null, "114" ],
          [ null, "122", null, "124" ],
          [ null, "132", null, "134" ]
        ],
        [
          [ null, "212", null, "214" ],
          [ null, "222", null, "224" ],
          [ null, "232", null, "234" ]
        ]
      ]
```

**Comment by mr-c** [comment]
Thanks for this report, seems to be the same issue  as #146

**Comment by jdidion** [comment]
I just don't understand - why bother having optional types at all if any type can effectively be optional?
