### ISSUE TITLE
Duplicate links in types

### ISSUE THREAD

**Issue by kinow** [common-workflow-language/cwl-v1.2#148]
Was looking at the docs today to try and help @Th3nn3ss on the issues he's working on [`wdl-cwl-translator`](https://github.com/common-workflow-lab/wdl-cwl-translator/issues/104), and noticed that the links in the `type` table column were getting repeated.

I had a brief look at the source here, but couldn't figure out where/how the duplication was happening.

1. open this link: https://www.commonwl.org/v1.2/Workflow.html#ExpressionTool;
2. scroll down to `requirements` in `4.3.18 ExpressionTool` > `Fields`;
3. check links like `ResourceRequirement` and `WorkReuse`.

![image](https://user-images.githubusercontent.com/304786/150760758-b756867b-78f4-4c93-879f-a4e09ce29a14.png)

Both links are pointing to: 

- https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement
- https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement

-Bruno

**Comment by mr-c** [comment]
Hello @kinow ; the "repeats" are part of the definition `map<"class", [long list of requirement types]` ; The hyperlink from `map` explains in more detail: https://www.commonwl.org/v1.2/Workflow.html#map

**Comment by kinow** [comment]
@mr-c aaahh! I had to look at the screenshot twice, squinting, but then I saw the `map<` in the middle of the links. Sorry for the noise :-)
