### ISSUE TITLE
Question: Are `WorkReuse` and other new process requirements not valid to be inherited to the CommandLineTool?

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwl-v1.2#197]
The [spec](https://www.commonwl.org/v1.2/CommandLineTool.html#Requirements_and_hints) says:

> If the substep is a CommandLineTool only the `InlineJavascriptRequirement`, `SchemaDefRequirement`, `DockerRequirement`, `SoftwareRequirement`, `InitialWorkDirRequirement`, `EnvVarRequirement`, `ShellCommandRequirement`, `ResourceRequirement` are valid.

But there are several process requirements that are accepted by the CommandLineTool but that are not in the above list: `LoadListingRequirement`, `WorkReuse`, `NetworkAccess`, `InplaceUpdateRequirement`, and `ToolTimeLimit`.

Is it inteded or can I send a pull request to add them?

**Comment by tetron** [comment]
I think those should be added.  Everything you listed was added in v1.1 which suggests this was probably an oversight.
