### ISSUE TITLE
Missing formatting for definitions in "Parameter references"?

### ISSUE THREAD

**Issue by fmigneault** [common-workflow-language/cwl-v1.2#206]
Looking at the definitions below, it seems like "code" formatting is missing. All items are written in plain strings.

https://www.commonwl.org/v1.2/CommandLineTool.html#Parameter_references <br>
![image](https://user-images.githubusercontent.com/19194484/199638451-7a778587-bfd7-4c04-8c39-38652e617ada.png)

**Comment by mr-c** [comment]
Sure, that could be added to https://github.com/common-workflow-language/cwl-v1.2/blob/1.2.1_proposed/concepts.md

**Comment by fmigneault** [comment]
Are the `::` after the parameter names to be preserved?

**Comment by tetron** [comment]
Yes the "::" is intentionally, it's an ad hoc BNF syntax https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form

**Comment by fmigneault** [comment]
@tetron 
Just to be sure, should it be `::=` instead as presented in that reference?

**Comment by tetron** [comment]
We could use `::=` but then you need to change the text of the spec
