### ISSUE TITLE
Solution to 64k file size limit

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-v1.2#26]
Presently we specify a 64k file size limit on file literals (file data coming from loadContents: true).  The purpose of this was to prevent users from accidentally overloading the workflow runner by trying to load the contents of a file that is very large (on the order of gigabytes).  The 64k limit was arbitrary ("64k should be enough for anybody").

Cwltool also interprets this limit to mean that file literals produced by javascript expressions are limited to 64k.  This turns out to be a substantial problem when you need to use InitialWorkDirRequirement to produce a parameter or configuration file that is larger than that.  There is a workaround of writing out individual pieces that are smaller than 64k and then having the tool combine them together to get the full list, but this introduces extra work and many users won't know how to do it.

Previous proposals included adjusting the limit in the spec, or introducing a new requirement to allow the user to set the limit.  These were both rejected in previous CWL meetings.

The proposal that got the most traction seemed to be to relax the limit for the cases of producing file contents from javascript expressions.  So I propose removing size enforcement except in the original case of using loadContents to read a file, and clarifying the behavior in the spec.

**Comment by mr-c** [comment]
This works for me, thank you for the nice write-up.

**Comment by tetron** [comment]
See #31

**Comment by azat-badretdin** [comment]
Looks like you implemented this, but I am still getting: 

````

INFO /blah/python3.9/bin/cwltool 3.1.20221109155812

....

 Reading file:///blah/github/repos/pgap/dev/expr/unit_tests/test_produce_enhanced_gff/annot.fna
 file is too large, loadContents limited to 65536 bytes

```

Am I missing some requirement?

**Comment by azat-badretdin** [comment]
According to this: https://github.com/common-workflow-language/cwl-v1.2/pull/31/commits/ea26603a30bdf91f14591376ede299e0ab6b5be6

```
If `contents` is set as a result of an Javascript expression,
        an `entry` in `InitialWorkDirRequirement`, or read in from
        `cwl.output.json`, there is no specified upper limit on the
        size of `contents`.  

```

So I figured I can try adding 

```
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.gff)
        writable: False
      - entry: $(inputs.fasta)
        writable: False

```
Did not help. 

CWL: https://github.com/ncbi/pgap/blob/dev/expr/produce_enhanced_gff.cwl
testdir: https://github.com/ncbi/pgap/tree/dev/expr/unit_tests/test_produce_enhanced_gff

```

**Comment by mr-c** [comment]
Hello @azat-badretdin 



> According to this: [ea26603](https://github.com/common-workflow-language/cwl-v1.2/commit/ea26603a30bdf91f14591376ede299e0ab6b5be6)
> 
> ```
> If `contents` is set as a result of an Javascript expression,
>         an `entry` in `InitialWorkDirRequirement`, or read in from
>         `cwl.output.json`, there is no specified upper limit on the
>         size of `contents`.  
> ```

I guess we need to clarify this further. The intent was that `File` literals in https://www.commonwl.org/v1.2/CommandLineTool.html#Dirent don't have a limit, but that files referenced still have the 64KiB limit on the `contents` field. Given your example, I think you'd be better off with a `CommandLineTool` using `bash` as the `baseCommand` and in `arguments` something like `cat $(inputs.gff.path) ; echo $(inputs.separator) ; cat $(inputs.fasta.path)` along with `stdout: $(inputs.output_name)`

**Comment by azat-badretdin** [comment]
Thanks for quick reply, Michael! I will switch to CommandLineTool (I suspected that I would have to from the very beginning, but I was reaching for the stars, given that pure ExpressionTool solution is more elegant to my taste).
