### ISSUE TITLE
amend JSON schema to allow new conformance tests

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-v1.2#265]
@fmigneault can you amend the JSON schema to allow these new conformance tests?

https://github.com/common-workflow-language/cwl-v1.2/actions/runs/5892148874/job/15980769336?pr=264#step:8:135

_Originally posted by @mr-c in https://github.com/common-workflow-language/cwl-v1.2/issues/264#issuecomment-1682409444_

**Comment by fmigneault** [comment]
@mr-c I cannot close it myself.
