### ISSUE TITLE
Wrong test failure assumption

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/cwl-v1.2#51]
The following two tests fail not because of the specified in the test case reason, but because workflows cannot be parsed due to `outputEval: "time passed"` line

https://github.com/common-workflow-language/cwl-v1.2/blob/993e40726177b0fe9e0b2484bd3630b3572f6951/conformance_tests.yaml#L2850

https://github.com/common-workflow-language/cwl-v1.2/blob/993e40726177b0fe9e0b2484bd3630b3572f6951/conformance_tests.yaml#L2876

**Comment by michael-kotliar** [comment]
@tetron @mr-c

**Comment by mr-c** [comment]
Good catch @michael-kotliar !

Here is a suggested fix:

``` diff
diff --git a/tests/timelimit-wf.cwl b/tests/timelimit-wf.cwl
index bd43ccc..168c10f 100644
--- a/tests/timelimit-wf.cwl
+++ b/tests/timelimit-wf.cwl
@@ -30,5 +30,4 @@ steps:
         o:
           type: string?
           outputBinding:
-            outputEval: "time passed"
-      
+            outputEval: $("time passed")
diff --git a/tests/timelimit4-wf.cwl b/tests/timelimit4-wf.cwl
index f7d1054..a03fa9d 100644
--- a/tests/timelimit4-wf.cwl
+++ b/tests/timelimit4-wf.cwl
@@ -33,4 +33,4 @@ steps:
         o:
           type: string?
           outputBinding:
-            outputEval: "time passed"
+            outputEval: $("time passed")
```

As per https://github.com/common-workflow-language/cwl-v1.2/issues/54 would you like to make a PR against https://github.com/common-workflow-language/cwl-v1.2/tree/1.2.1_proposed ?
