### ISSUE TITLE
`run_test.sh` seems to be old

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwl-v1.2#70]
`run_test.sh` in this repository lacks several options such as `--self`, `--badgedir` and `--tags` that are available in [`run_test.sh`](https://github.com/common-workflow-language/common-workflow-language/blob/main/run_test.sh) in [cwl-v1.0](https://github.com/common-workflow-language/common-workflow-language) repository.
It would be nice if the test suite is self-contained, that is, cloning this repository and running `run_test.sh` are enough to test platforms.

Can we simply overwrite `run_test.sh` in this repository with the script in [cwl-v1.0](https://github.com/common-workflow-language/common-workflow-language)?

**Comment by mr-c** [comment]
> Can we simply overwrite `run_test.sh` in this repository with the script in [cwl-v1.0](https://github.com/common-workflow-language/common-workflow-language)?

Probably! I'd review that PR, yes
