### ISSUE TITLE
Breaking change introduced in loadContents in v1.2

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/cwl-v1.2#77]
As I was going through the change log I noticed that loadContents should start failing if a file is greater than 64kb, while previously it simply truncated any file contents past the first 64kb. I couldn't find any discussion on git issues for this change, I was wondering if there was some particular reason for introducing this change. If not, does it make sense to restore previous behaviour in CWL v1.2.1?

**Comment by tetron** [comment]
This was discussed extensively during the 1.2 draft process.  It may have been primarily through meetings, though.

The rationale is that truncating file contents lead to surprising results.  In theory, one could use this feature to read the header of a large file, but there's no evidence that anyone did anything like that.  In practice, what people actually used this feature for was to do things like read each line of a file into an array of strings.  Then if a file was too large it would be silently truncated, leading to surprising results and generating a support request.  We decided it was better to error out in that case.

**Comment by bogdang989** [comment]
Ok, thanks for the info.
