### ISSUE TITLE
Ambiguous spec: Dirent with `writable: true` without InplaceUpdateRequirement

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/cwl-v1.2#82]
The [spec of `InplaceUpdateRequirement`](https://www.commonwl.org/v1.2/Workflow.html#InplaceUpdateRequirement) says:

> That is, as an optimization, files may be destructively modified in place as opposed to copied and updated.

However, there are no descriptions whether destructive modification is allowed in the case of [`Dirent.writable`](https://www.commonwl.org/v1.2/Workflow.html#Dirent) is `true` but without `InplaceUpdateRequirement`.

It would be nice if it is clarified in the spec.

**Comment by mr-c** [comment]
@tom-tan Thanks for bringing this to our attention.

without `InplaceUpdateRequirement` then destructive modification of user input files is not allowed. In the case of `Dirent.writable` being `true` then a copy must be made if there is no `InplaceUpdateRequirement` present.

Yes, I agree this should be made more explicit in the spec. PRs that accomplish that will be reviewed favourably for CWL v1.2.1
