### ISSUE TITLE
[Conformance test] Stdout behavior with chained commands

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/cwl-v1.2#95]
If a command line tool runs `echo a && echo b` and stdout is specified as `out.txt`, the contents of out.txt should be `a b`
An executor might just run `echo a && echo b > out.txt` which is incorrect and would just add `b` to `out.txt`. A conformance test should clear this up.

**Comment by mr-c** [comment]
This will presumably require https://www.commonwl.org/v1.2/CommandLineTool.html#ShellCommandRequirement

**Comment by mr-c** [comment]
Places to review the spec wording
https://www.commonwl.org/v1.2/CommandLineTool.html#Running_a_Command
`stdout` from https://www.commonwl.org/v1.2/CommandLineTool.html#CommandLineTool and maybe https://www.commonwl.org/v1.2/CommandLineTool.html#stdout
